name: object_serializer
description: A serializer (with caching support) of any static (generic) complex data that can be represented as simpler data.
repository:  https://github.com/mezoni/object_serializer
version: 0.1.3
environment:
  sdk: '>=2.17.0 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  tuple: ^2.0.0
